server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?serverTimezone=GMT
    username: root
    password: cjh990105
    driver: com.mysql.cj.jdbc.Driver
  application:
    name: service-provider  # 将来会作为微服务的名称
mybatis:
  type-aliases-package: cn.itcast.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: true  # 服务提供方启动时，会检测该参数是否为true，为true就注册给eureka
  instance:
    lease-expiration-duration-in-seconds: 15   #  服务失效时间，默认值90秒
    lease-renewal-interval-in-seconds: 5    # 服务续约(renew)的间隔，默认为30秒